export const SET_CREATE_EVENT_STATUS = 'SET CREATE EVENT STATUS';
export const SET_CREATE_EVENT_ERROR_MSG = 'SET CREATE EVENT ERROR MSG';
export const SET_CREATED_EVENT = 'SET CREATED EVENT';
export const SET_IS_RECURRING = 'SET RECURRING EVENT';
export const SET_ALL_EVENTS = 'SETTING ALL EVENTS';
