export const SET_USER = 'SET USER';
export const UNSET_USER = 'UNSET USER';
export const SET_LOGIN_STATUS = 'SET LOGIN STATUS';
export const SET_LOGIN_ERROR_MSG = 'SET LOGIN ERROR MSG';
export const SET_CREATE_USER_STATUS = 'SET CREATE USER STATUS';
export const SET_CREATE_USER_ERROR_MSG = 'SET CREATE USER ERROR MSG';
